length_violation_reward: 0.0
double_victim_access_reward: 0.0
victim_access_reward: 0.0
victim_miss_reward: 0.0
correct_reward: 1.0
wrong_reward: -1.0
step_reward: 0.0
no_guess_reward: -200.0

cache_state_reset: false
reset_observation: false

verbose: 0
ev_mode: false
force_victim_hit: false
flush_inst: false
allow_victim_multi_access: true
allow_empty_victim_access: true
attacker_addr_s: 4 
attacker_addr_e: 11
victim_addr_s: 0
victim_addr_e: 0 
reset_limit: 1

cache_configs:
  architecture:
    word_size: 1
    block_size: 1
    write_back: true
  cache_1:
    blocks: 2
    associativity: 2
    hit_time: 1
    rep_policy: "lru"
  cache_1_core_2:  
    blocks: 2
    associativity: 2
    hit_time: 1
    rep_policy: "lru"
  cache_2:
    blocks: 4
    associativity: 4
    hit_time: 16
  mem:
    hit_time: 1000

window_size: 160
episode_length: 160
cc_hunter_check_length: 8

threshold: 0.75
cc_hunter_coeff: 0.0
