m_server_name: "m_server"
m_server_addr: "127.0.0.1:4411"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:4412"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:4413"

train_device: "cuda:0"
infer_device: "cuda:1"

num_train_rollouts: 4
num_train_workers: 4

num_eval_rollouts: 2
num_eval_workers: 2

# replay_buffer_size: 262144
replay_buffer_size: 65536
prefetch: 0

batch_size: 512
lr: 3e-4
# learning_starts: 65536
push_every_n_steps: 10

num_epochs: 1000
steps_per_epoch: 3000

num_eval_episodes: 20

train_seed: 123
eval_seed: 456

table_view: False

env_config:
  length_violation_reward: -2
  double_victim_access_reward: -1e-2
  victim_access_reward: -1e-2
  correct_reward: 1
  wrong_reward: -2
  step_reward: -1e-2

  verbose: 0
  force_victim_hit: false
  flush_inst: false
  allow_victim_multi_access: true
  allow_empty_victim_access: false

  attacker_addr_s: 0
  attacker_addr_e: 15
  victim_addr_s: 0
  victim_addr_e: 7
  reset_limit: 1

  cache_configs:
    architecture:
      word_size: 1
      block_size: 1
      write_back: true
    cache_1:
      blocks: 8
      associativity: 8
      hit_time: 1
      rep_policy: "lru"
    mem:
      hit_time: 1000 

model_config:
  latency_dim: 3
  victim_acc_dim: 2
  action_dim: 200
  step_dim: 80
  window_size: 40
  action_embed_dim: 16
  step_embed_dim: 4
  hidden_dim: 128
  output_dim: -1
  num_blocks: 1
