num_episodes: 1000
seed: 123 #123 1234 12345

attacker_checkpoint: ""
detector_checkpoint: ""


deterministic_policy: true

# for train  # TODO: Which trace dataset Jiaxun used for 1c-svm?
trace_files: [
 
    "/home/geunbae/data/MACTA/train/spectrace_500-2M_500-4M.txt",
    "/home/geunbae/data/MACTA/train/spectrace_502-2M_502-4M.txt",
    "/home/geunbae/data/MACTA/train/spectrace_505-2M_505-4M.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_502_2000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_505_2000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_502_505_2000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_502_6000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_505_6000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_502_505_6000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_502_10000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_500_505_10000000.txt",
    "/home/geunbae/data/MACTA/train/spectrace_502_505_10000000.txt",

    ]
  
# for testing
test_trace_files: [

    #'/home/geunbae/data/MACTA_offset/prime/self_548_p/548-2M_548-4M+1187.txt',
    '/home/geunbae/data/MACTA_offset/prime/self_631_p/631-2M_631-4M+1187.txt',
    #'/home/geunbae/data/MACTA_offset/prime/self_638_p/638-2M_638-4M+1187.txt',
    #'/home/geunbae/data/MACTA_offset/prime/self_641_p/641-2M_641-4M+1187.txt',
    #'/home/geunbae/data/MACTA_offset/nonprime/self_548_np/548-2M_548-4M+31.txt',
    #'/home/geunbae/data/MACTA_offset/nonprime/self_631_np/631-2M_631-4M+31.txt',
    #'/home/geunbae/data/MACTA_offset/nonprime/self_638_np/638-2M_638-4M+31.txt', 
    #'/home/geunbae/data/MACTA_offset/nonprime/self_641_np/641-2M_641-4M+31.txt',
  ]

trace_limit: 2000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
