num_episodes: 1000
seed: 123 #123 1234 12345

attacker_checkpoint: ""
detector_checkpoint: ""


deterministic_policy: true


trace_files: [
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500-2M_500-4M.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_502-2M_502-4M.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_505-2M_505-4M.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_502_2000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_505_2000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_502_505_2000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_502_6000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_505_6000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_502_505_6000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_502_10000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_500_505_10000000.txt",
    #"/checkpoint/yangxm/cache/ICLR2023/data/spectrace_502_505_10000000.txt",

    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500-2M_500-4M.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_502-2M_502-4M.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_505-2M_505-4M.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_2000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_2000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_2000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_6000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_6000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_6000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_10000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_10000000.txt",
    #"/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_10000000.txt",

    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_505-2M_505-4M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_607-2M_607-4M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_631-2M_631-4M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_641-2M_641-4M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_505-2M_631-2M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_505-2M_641-2M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_505_607_2000000.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_607-2M_631-2M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_607-2M_641-2M.txt",
    "/u/jxcui/Documents/spectrace_bug_fix/spectrace_631-2M_641-2M.txt",

]
trace_limit: 2000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
