num_episodes: 1000
seed: 123 #123 1234 12345

attacker_checkpoint: ""
detector_checkpoint: ""


deterministic_policy: true

# for train  # TODO: Which trace dataset Jiaxun used for 1c-svm?
trace_files: [
 
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+109.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+1187.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+12487.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+1627.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+181.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+184957.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+193.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+2153.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+258161.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+266137.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+269.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+2999.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+3709.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+39749.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+491.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+5881.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+617249.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+62501.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+63409.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+654539.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+661.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+67.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+6883.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+7069.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+79.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+8623.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+877.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+89.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+91393.txt",
    #"/home/geunbae/data/self_641_p/641-2M_641-4M+9413.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+109.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+1187.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+12487.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+1627.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+181.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+184957.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+193.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+2153.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+258161.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+266137.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+269.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+2999.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+3709.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+39749.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+491.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+5881.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+617249.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+62501.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+63409.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+654539.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+661.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+67.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+6883.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+7069.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+79.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+8623.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+877.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+89.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+91393.txt",
    #"/home/geunbae/data/self_548_p/548-2M_548-4M+9413.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+109.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+1187.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+12487.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+1627.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+181.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+184957.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+193.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+2153.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+258161.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+266137.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+269.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+2999.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+3709.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+39749.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+491.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+5881.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+617249.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+62501.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+63409.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+654539.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+661.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+67.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+6883.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+7069.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+79.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+8623.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+877.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+89.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+91393.txt",
    #"/home/geunbae/data/self_631_p/631-2M_631-4M+9413.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+109.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+1187.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+12487.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+1627.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+181.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+184957.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+193.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+2153.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+258161.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+266137.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+269.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+2999.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+3709.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+39749.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+491.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+5881.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+617249.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+62501.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+63409.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+654539.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+661.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+67.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+6883.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+7069.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+79.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+8623.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+877.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+89.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+91393.txt",
    #"/home/geunbae/data/self_638_p/638-2M_638-4M+9413.txt"
    ]
  
# for testing
test_trace_files: []

trace_limit: 2000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
