m_server_name: "m_server"
m_server_addr: "127.0.0.1:14711"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14722"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14733"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4711"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4722"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4733"

train_device: "cuda:1"
infer_device: "cuda:2"
train_device_d: "cuda:1" #"cuda:2"
infer_device_d: "cuda:0" #"cuda:3"

num_train_rollouts: 72 #72 #48 #24
num_train_workers: 24  #24

num_eval_rollouts: 12 #2
num_eval_workers: 4 #2

#attacker_checkpoint: "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-07-21/00-03-30/attacker-2949.pth"
attacker_checkpoint: "/localdata/erfan/research/AutoCAT/src/rlmeta/macta/outputs/2024-01-17/12-24-40/ppo_agent-99.pth"
#detector_checkpoint: "/localdata/vishnu/facebookresearch/macta/checkpoints/macta_attacker_pretrain/attacker-99.pth"

trace_files: [
  "/localdata/vishnu/SPEC_traces/spectrace_500-2M_500-4M.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_502-2M_502-4M.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_505-2M_505-4M.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_502_2000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_505_2000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_502_505_2000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_502_6000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_505_6000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_502_505_6000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_502_10000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_500_505_10000000.txt",
  "/localdata/vishnu/SPEC_traces/spectrace_502_505_10000000.txt",
  # "/localdata/vishnu/SPEC_traces/spectrace_548-2M_548-4M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_631-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_638-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_641-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_631-2M_631-4M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_631-2M_638-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_631-2M_641-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_638-2M_638-4M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_638-2M_641-2M.txt",
  #"/localdata/vishnu/SPEC_traces/spectrace_641-2M_641-4M.txt",
]
trace_limit: 2000000
legacy_trace_format: false

replay_buffer_size: 262144
prefetch: 2

batch_size: 512
lr: 1e-4
entropy_coeff: 0.03 # default 0.01
learning_starts: 65536
push_every_n_steps: 10

dual_clip: 3.0

num_epochs: 1000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

optimizer:
  lr: 1e-4
  weight_decay: 0.0
defaults:
  - env_config: macta_env
  - model_config: new_transformer
