num_episodes: 10
seed: 123 #123 1234 12345

###### Important: Use absolute path here as hydra will operate in a new directory.

###### Used in head-to-head mode
# attacker_checkpoint: "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp2/attacker-1849.pth"
# cyclone_path: "/localdata/vishnu/facebookresearch/macta/checkpoints/cyclone_oneclass_svm/exp3/cyclone.pkl"
# detector_checkpoint: "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp1/detector-1799.pth"

###### Used in Tournament
attackers: [ 
            # ["PrimeProbe", ""],
#            ["IBRPPO-attacker-1","/localdata/vishnu/facebookresearch/macta/checkpoints/ibrppo/exp1/attacker-1849.pth"],
#            ["IBRPPO-attacker-2","/localdata/vishnu/facebookresearch/macta/checkpoints/ibrppo/exp2/attacker-1849.pth"],
            # ["IBRPPO-attacker-3","/localdata/erfan/macta/checkpoints/ibrppo/exp3/attacker-1849.pth"],
#            ["AutoCAT-1","/localdata/vishnu/facebookresearch/macta/checkpoints/autocat/exp1/ppo_agent-99.pth"],
#            ["AutoCAT-2","/localdata/vishnu/facebookresearch/macta/checkpoints/autocat/exp2/ppo_agent-99.pth"],
            # ["AutoCAT-3","/localdata/erfan/macta/checkpoints/autocat/exp3/ppo_agent-99.pth"],
#            ["MACTA-attacker-1", "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp1/attacker-1849.pth"],
#            ["MACTA-attacker-2", "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp2/attacker-1849.pth"],
            # ["MACTA-attacker-3", "/localdata/erfan/macta/checkpoints/macta/exp3/attacker-1849.pth"],
            # ["Benign", ""],
            ["MACTA-attacker-4", "/localdata/erfan/research/AutoCAT/src/rlmeta/macta/outputs/2024-03-06/18-04-39/attacker-749.pth"]
            ]
detectors: [ 
#            ["IBRPPO-detector-1","/localdata/vishnu/facebookresearch/macta/checkpoints/ibrppo/exp1/detector-1799.pth"],
#            ["IBRPPO-detector-2","/localdata/vishnu/facebookresearch/macta/checkpoints/ibrppo/exp2/detector-1799.pth"],
#            ["IBRPPO-detector-3","/localdata/vishnu/facebookresearch/macta/checkpoints/ibrppo/exp3/detector-1799.pth"],
#            ["MACTA-detector-1", "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp1/detector-1799.pth"],
#            ["MACTA-detector-2", "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp2/detector-1799.pth"],
#            ["MACTA-detector-3", "/localdata/vishnu/facebookresearch/macta/checkpoints/macta/exp3/detector-1799.pth"],
            #["MACTA-detector-4", "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-08-06/03-05-30/detector-2999.pth"],
            #["MACTA-detector-5", "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-08-06/03-05-30/detector-2750.pth"],
            #["MACTA-detector-6", "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-08-06/03-05-30/detector-2499.pth"],
            #["MACTA-detector-7", "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-08-06/03-05-30/detector-2250.pth"],
            #["MACTA-detector-8", "/localdata/vishnu/facebookresearch/macta/src/rlmeta/macta/outputs/2023-08-06/03-05-30/detector-1999.pth"],
            # ["MACTA-detector-8", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-2999.pth"],
            # ["MACTA-detector-9", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-2750.pth"],
            # ["MACTA-detector-10", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-2499.pth"],
            # ["MACTA-detector-11", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-2250.pth"],
            # ["MACTA-detector-12", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-1999.pth"],
            # ["MACTA-detector-13", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-1750.pth"],
            # ["MACTA-detector-14", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-1499.pth"],
            # ["MACTA-detector-15", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-1250.pth"],
            # ["MACTA-detector-16", "/localdata/erfan/research/AutoCAT/src/rlmeta/macta/outputs/2024-02-26/09-23-11/detector-799.pth"],
            # ["MACTA-detector-17", "/localdata/erfan/macta/src/rlmeta/macta/outputs/2023-12-22/11-10-17/detector-499.pth"],
            # ["Locker", ""],
            ["randomLocker", ""],
#            ["Cyclone-1", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-02-25/16-47-09/cyclone.pkl"],
#            ["Cyclone-2", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-02-25/16-47-28/cyclone.pkl"],
#            ["Cyclone-3", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-02-25/16-47-42/cyclone.pkl"],
#            ["Cyclone-4", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-04-11/19-12-17/cyclone.pkl"],
#            ["Cyclone-5", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-04-11/19-12-32/cyclone.pkl"],
#            ["Cyclone-6", "/localdata/vishnu/facebookresearch/macta/checkpoints/2023-04-11/19-12-44/cyclone.pkl"],
#            ["CC-Hunter-1", "n/a"],
#            ["CC-Hunter-2", "n/a"],
#            ["CC-Hunter-3", "n/a"],
#            ["None", "None"],
#            ["None", "None"],
#            ["None", "None"],
            ]

deterministic_policy: true

trace_file: ""
trace_files: [
    #Train
    #"/localdata/vishnu/SPEC_traces/spectrace_500-2M_500-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_502-2M_502-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_505-2M_505-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_500_502_2000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_500_505_2000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_502_505_2000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_500_502_6000000.txt",
    # "/localdata/vishnu/SPEC_traces/spectrace_500_505_6000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_502_505_6000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_500_502_10000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_500_505_10000000.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_502_505_10000000.txt",
    
    #VAL
    #"/localdata/vishnu/SPEC_traces/spectrace_549_607_2000000.txt",
    
    #TEST
    # "/localdata/vishnu/SPEC_traces/spectrace_548-2M_548-4M.txt",
    "/localdata/vishnu/SPEC_traces/spectrace_631-2M_631-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_638-2M_638-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_641-2M_641-4M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_631-2M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_638-2M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_548-2M_641-2M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_631-2M_638-2M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_631-2M_641-2M.txt",
    #"/localdata/vishnu/SPEC_traces/spectrace_638-2M_641-2M.txt",
    ]
trace_limit: 4000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
