num_episodes: 200
seed: 123 #123 1234 12345

### AutoCAT attacker ###
# scenario 1 (1s4w, v:0/e, a:4-7)

# scenario 2 (1s4w, v:0/e, a:0-7)
#attacker_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/18-24-05/ppo_agent-699.pth" 

# scenario 3 (1s8w, v:0/e, a:0-15)

### MACTA attacker ###
# scenario 1 (1s4w, v:0/e, a:4-7)

# scenario 2 (1s4w, v:0/e, a:0-7)
#attacker_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/attacker-548.pth" # atk success 89%
attacker_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/attacker-749.pth" # atk success 63%

# scenario 3 (1s8w, v:0/e, a:0-15)
#attacker_checkpoint: ""


### MACTA defender ### 
# scenario 1 (1s4w, v:0/e, a:4-7)

# scenario 2 (1s4w, v:0/e, a:0-7)
defender_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/defender-799.pth"

# scenario 3 (1s8w, v:0/e, a:0-15)


#MACTA-fp10
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/20-20-00/attacker-2049.pth" 
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-35-10/detector-1999.pth" #69% macta4
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-51/detector-1999.pth" #50% macta5
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-06/18-06-41/detector-1999.pth" #32% no init
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-06/18-05-26/detector-1999.pth" #55% no init
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-07/16-29-46/detector-1999.pth" #1% no init

#TEST

#attacker_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-25/06-30-49/attacker-2049.pth"
#attacker_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-14/14-51-08/attacker-107.pth'
#attacker_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-15/14-45-36/attacker-601.pth'
#attacker_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-16/17-30-24/attacker-649.pth'
#defender_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-25/06-31-25/detector-1999.pth"
#defender_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-14/14-51-08/defender-150.pth'
#defender_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-15/14-45-36/defender-650.pth'
#defender_checkpoint: '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-16/17-30-24/defender-599.pth'

#IBRPPO-fp10
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/attacker-2049.pth"
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-23-31/detector-1999.pth"

#AutoCAT
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-39-43/ppo_agent-99.pth"




#Tournament
attackers: [ 
            ["PrimeProbe", ""],
            #['AutoCAT-1','/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-17/18-00-45/ppo_agent-298.pth']
            #["AutoCAT-2","/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/18-24-05/ppo_agent-699.pth"],
            #['MACTA-attacker-1', '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/attacker-714.pth']
            #["MACTA-attacker-1", '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-15/14-45-36/attacker-739.pth'],
            #["MACTA-attacker-2", '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-16/17-30-24/attacker-749.pth']
            #["Benign", ""],
           
            ]
defenders: [ #["IBRPPO-detector-1","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/detector-1999.pth"],
             #["MACTA-defender-1", "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-15/14-45-36/defender-799.pth"],
             #['MACTA-defender-1', '/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/defender-699.pth']
             #["MACTA-defender-2", "/home/geunbae/CacheSimulator/src/rlmeta/macta/train/outputs/2023-04-18/00-16-56/defender-799.pth"],
             #["CC-Hunter-1", "n/a"],
             #["CC-Hunter-2", "n/a"],
             #["CC-Hunter-3", "n/a"],
             ["None", "None"],
            ]

deterministic_policy: true # false
#trace_file: "/u/jxcui/remix3.txt" # TODO
trace_files: [

    # MACTA test set
    '/home/geunbae/data/MACTA/test/spectrace_548-2M_548-4M.txt',  # check
    #'/home/geunbae/data/MACTA/test/spectrace_631-2M_631-4M.txt',  # check
    #'/home/geunbae/data/MACTA/test/spectrace_638-2M_638-4M.txt',  # check
    #'/home/geunbae/data/MACTA/test/spectrace_641-2M_641-4M.txt',  # check
    #'/home/geunbae/data/MACTA/test/spectrace_548-2M_631-2M.txt',  # check
    #'/home/geunbae/data/MACTA/test/spectrace_548-2M_638-2M.txt',
    #'/home/geunbae/data/MACTA/test/spectrace_548-2M_641-2M.txt',
    #'/home/geunbae/data/MACTA/test/spectrace_631-2M_638-2M.txt',
    #'/home/geunbae/data/MACTA/test/spectrace_631-2M_641-2M.txt',
    #'/home/geunbae/data/MACTA/test/spectrace_638-2M_641-2M.txt',
    ]
trace_limit: 1000000
legacy_trace_format: false

defaults:
  - env_config: macta_def_1s4w  # TODO 
  - model_config: transformer
