num_episodes: 1000
seed: 123 #123 1234 12345

#cyclone
#cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-13/cyclone.pkl"
#cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-23/cyclone.pkl"
#cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-30/cyclone.pkl"

#MACTA-fp10
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/20-20-00/attacker-2049.pth" 
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-03-48/attacker-2049.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-04-01/attacker-2049.pth"
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/20-20-00/detector-1999.pth" #98%
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-03-48/detector-1999.pth" #96%
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-04-01/detector-1999.pth" #97%
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-35-10/detector-1999.pth" #69% macta4
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-51/detector-1999.pth" #50% macta5
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-06/18-06-41/detector-1999.pth" #32% no init
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-06/18-05-26/detector-1999.pth" #55% no init
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-07/16-29-46/detector-1999.pth" #1% no init

#TEST

#attacker_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-25/06-30-49/attacker-2049.pth"
#attacker_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/outputs/2023-02-06/10-26-26/attacker-2949.pth" 
#detector_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-25/06-31-25/detector-1999.pth"
#detector_checkpoint: "/home/geunbae/CacheSimulator/src/rlmeta/outputs/2023-02-06/10-26-26/detector-2999.pth"


#IBRPPO-fp10
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/attacker-2049.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-24-54/attacker-2049.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-23-31/attacker-2049.pth"
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/detector-1999.pth"
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-24-54/detector-1999.pth"
#detector_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-23-31/detector-1999.pth"

#AutoCAT
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-39-43/ppo_agent-99.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-32/ppo_agent-99.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-57/ppo_agent-99.pth"




#Tournament
attackers: [ 
            #["PrimeProbe", ""],
            #["IBRPPO-attacker-1","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/attacker-2049.pth"],
            #["IBRPPO-attacker-2","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-24-54/attacker-2049.pth"],
            #["IBRPPO-attacker-3","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-23-31/attacker-2049.pth"],
            #["AutoCAT-1","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-39-43/ppo_agent-99.pth"],
            #["AutoCAT-2","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-32/ppo_agent-99.pth"],
            #["AutoCAT-3","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-57/ppo_agent-99.pth"],
            #["MACTA-attacker-1", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/20-20-00/attacker-2049.pth"],
            #["MACTA-attacker-2", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-04-01/attacker-2049.pth"],
            #["MACTA-attacker-3", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-35-10/attacker-2049.pth"],
            #["MACTA-attacker-4", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-51/attacker-2049.pth"],
             ["Benign", ""],
            # ["None", "None"]
           
            ]
detectors: [ #["IBRPPO-detector-1","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-25-18/detector-1999.pth"],
             #["IBRPPO-detector-2","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-24-54/detector-1999.pth"],
             #["IBRPPO-detector-3","/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-01/05-23-31/detector-1999.pth"],
             #["MACTA-detector-1", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/20-20-00/detector-1999.pth"],
             #["MACTA-detector-2", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/03-04-01/detector-1999.pth"],
             #["MACTA-detector-3", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-35-10/detector-1999.pth"],
             #["MACTA-detector-4", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-03/14-57-51/detector-1999.pth"],
             #["Cyclone-1", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-15/21-30-00/cyclone.pkl"],
             #["Cyclone-2", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-15/21-30-13/cyclone.pkl"],
             #["Cyclone-3", "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-11-15/21-31-39/cyclone.pkl"],
             #["CC-Hunter-1", "n/a"],
             #["CC-Hunter-2", "n/a"],
             #["CC-Hunter-3", "n/a"],
             #["None", "None"],
             #["None", "None"],
             ["None", "None"]
            ]

deterministic_policy: true
#trace_file: 'home/geunbae/data/548-2M_548_4M+67.txt' #'/home/geunbae/data/631-2M_631-4M.txt'  # "/u/jxcui/remix3.txt" 
trace_files: [

    # Visualization for self mixes: 548, 631, 638, 641 
    #'/home/geunbae/data/MACTA/test/spectrace_548-2M_548-4M.txt'
    #'/home/geunbae/data/MACTA/test/spectrace_631-2M_631-4M.txt'
    #'/hdd/shared_traces_022023_631/spectrace_631-2M_631-4M.txt'
    '/home/geunbae/data/MACTA/test/spectrace_638-2M_638-4M.txt'
    #'/home/geunbae/data/MACTA/test/spectrace_641-2M_641-4M.txt'

    # Visualization for self-mix w/ prime offset
    #'/home/geunbae/data/MACTA_offset/prime/self_548_p/548-2M_548-4M+1187.txt'
    #'/home/geunbae/data/MACTA_offset/prime/self_631_p/631-2M_631-4M+1187.txt'
    #'/home/geunbae/data/MACTA_offset/prime/self_638_p/638-2M_638-4M+1187.txt'
    #'/home/geunbae/data/MACTA_offset/prime/self_641_p/641-2M_641-4M+1187.txt'

    # Visualization for self-mix w/ non-prime offset
    #'/home/geunbae/data/MACTA_offset/nonprime/self_548_np/548-2M_548-4M+31.txt'
    #'/home/geunbae/data/MACTA_offset/nonprime/self_631_np/631-2M_631-4M+31.txt'
    #'/home/geunbae/data/MACTA_offset/nonprime/self_638_np/638-2M_638-4M+31.txt' 
    #'/home/geunbae/data/MACTA_offset/nonprime/self_641_np/641-2M_641-4M+31.txt'

    ]
trace_limit: 4000000
legacy_trace_format: false

defaults:
  - env_config: macta_env
  - model_config: transformer
