device: "cuda"

logger:
  exp_name: ppo_attack
  exp_suffix:

collector:
  total_frames: 10_000_000
  frames_per_batch: 1024
  num_workers: 32
  device: "cuda"

rb:
  prefetch:
  batch_size: 64

optimizer:
  lr: 2e-4
  weight_decay: 0.0

loss:
  entropy_coeff: 0.1
  clip_grad_norm: 1000.0
  loss_critic_type: l2

num_epochs: 5

seed: null

eval_freq: 10

defaults:
  - env_config: hpca_ae_exp_4_1
  - model_config: transformer
