device: "cuda"

collector:
  total_frames: 10_000_000
  frames_per_batch: 1024
  num_workers: 16

rb:
  size:
  prefetch: 8
  batch_size: 64

optimizer:
  lr: 2e-4

# what to do with this?
entropy_coeff: 0.02

num_epochs: 5

seed: null

eval_freq: 10

defaults:
  - env_config: hpca_ae_exp_4_1
  - model_config: transformer
