m_server_name: "m_server"
m_server_addr: "127.0.0.1:14711"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14722"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14733"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4711"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4722"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4733"

detector_checkpoint: ""
attacker_checkpoint: ""
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/attacker-249.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/detector-2584.pth" #hard flag
#FP-PPO############################################                                                                                             
#fp-5x-1                                                                                                                                        
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/attacker-1949.pth" #hard flag 5*fp             
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-1999.pth" #hard flag                  
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-999.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-499.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-2399.pth" #hard flag

#fp-5x-2                                                                                                                                        
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/attacker-1949.pth" #hard flag 5*fp             
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/detector-1999.pth" #hard flag                   
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/detector-999.pth" #hard flag 
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/detector-499.pth" #hard flag 

#fp-5x-3
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/detector-1999.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/detector-999.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/detector-499.pth" #hard flag

train_device: "cuda:0"
infer_device: "cuda:1"
train_device_d: "cuda:2" #"cuda:2"
infer_device_d: "cuda:3" #"cuda:3"
num_train_rollouts: 48 #72 #48 #24
num_train_workers: 24  #24

num_eval_rollouts: 12 #2
num_eval_workers: 4 #2

# replay_buffer_size: 262144
# replay_buffer_size: 131072
replay_buffer_size: 65536
#replay_buffer_size: 1024
prefetch: 2

batch_size: 512
lr: 1e-4 #1e-4
entropy_coeff: 0.03 # default 0.01
# learning_starts: 65536
push_every_n_steps: 10

num_epochs: 3000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

defaults:
  # - env_config: config_exp2
  # - env_config: config_exp3
  # - env_config: config_exp4
  # - env_config: config_exp5
  # - env_config: config_exp6
  # - env_config: config_exp7
  # - env_config: config_exp8
  # - env_config: config_exp9
  - env_config: config_exp61
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp10
  # - env_config: config_exp11
  # - env_config: config_exp12
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  # - env_config: config_exp_14_nextline
  # - env_config: config_exp_remap_baseline
  # - env_config: config_exp_remap_baseline2
  # - env_config: config_exp_ceaser_distributed
  - model_config: experiments
