m_server_name: "m_server"
m_server_addr: "127.0.0.1:14744"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14755"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14766"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4744"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4755"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4766"

train_device: "cuda:0"
infer_device: "cuda:1"
train_device_d: "cuda:2" #"cuda:2"
infer_device_d: "cuda:3" #"cuda:3"
num_train_rollouts: 8 #72 #48 #24
num_train_workers: 8  #24

num_eval_rollouts: 1 #2
num_eval_workers: 1 #2

attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/18-20-26/ppo_agent-49.pth"
#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-12-02/02-27-19/attacker-99.pth"
#attacker_checkpoint: ""

# replay_buffer_size: 262144
# replay_buffer_size: 131072
#replay_buffer_size: 262144
replay_buffer_size: 1024 
prefetch: 2

batch_size: 512
lr: 1e-4 #1e-4
entropy_coeff: 0.03 # default 0.01
learning_starts: 65536
push_every_n_steps: 10

num_epochs: 3000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

defaults:
  # - env_config: config_exp2
  # - env_config: config_exp3
  # - env_config: config_exp4
  # - env_config: config_exp5
  # - env_config: config_exp6
  # - env_config: config_exp7
  # - env_config: config_exp8
  # - env_config: config_exp9
  
  - env_config: config_covert
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp10
  # - env_config: config_exp11
  # - env_config: config_exp12
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  # - env_config: config_exp_14_nextline
  # - env_config: config_exp_remap_baseline
  # - env_config: config_exp_remap_baseline2
  # - env_config: config_exp_ceaser_distributed
  - model_config: experiments
  - sender_model_config: sender_exp
  # - model_config: resnet_lru_8way
