m_server_name: "m_server"
m_server_addr: "127.0.0.1:4411"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:4412"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:4413"

train_device: "cuda:0"
infer_device: "cuda:1"

num_train_rollouts: 24
num_train_workers: 48

num_eval_rollouts: 2
num_eval_workers: 4

# replay_buffer_size: 262144
replay_buffer_size: 131072
# replay_buffer_size: 65536
prefetch: 2

batch_size: 512

optimizer:
  name: "Adam"
  args:
    lr: 1e-4

learning_starts: 65536
model_push_period: 10

entropy_coeff: 0.01

num_epochs: 3000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

defaults:
  # - env_config: lru_8way
  # - env_config: config_exp2
  # - env_config: config_exp3
  # - env_config: config_exp4
  # - env_config: config_exp5
  # - env_config: config_exp6
  # - env_config: config_exp7
  # - env_config: config_exp8
  # - env_config: config_exp9
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp10
  # - env_config: config_exp11
  # - env_config: config_exp12
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  # - env_config: config_exp_14_nextline
  # - env_config: config_exp_remap_baseline
  # - env_config: config_exp_remap_baseline2
  # - env_config: config_exp_ceaser_distributed
  # - env_config: config_exp_real
  - env_config: hpca_exp_1.yaml
  # - env_config: hpca_exp_2.yaml
  # - env_config: hpca_exp_3.yaml
  # - env_config: hpca_exp_4.yaml
  # - env_config: hpca_exp_5.yaml
  # - env_config: hpca_exp_6.yaml
  # - env_config: hpca_exp_7.yaml
  # - env_config: hpca_exp_multicore_1.yaml
  # - env_config: hpca_v_1.yaml
  # - env_config: hpca_v_2.yaml
  - model_config: experiments
