num_episodes: 1000
seed: 1234

exp_name: "/2022-07-26/14-03-38/wandb/run-20220726_140343-2wwnweyz/" # entangle-pool
#exp_name: "2022-07-26/16-25-20/wandb/run-20220726_162520-2jqwd1e9/" # entangle
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-07-26/16-25-20/wandb/run-20220726_162520-2jqwd1e9/files/attacker-model-99.th"
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-07-26/14-03-38/wandb/run-20220726_140343-2wwnweyz/files/detector-model-599.th"
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-07/23-59-58/attacker-442.pth"

#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/10-28-40/attacker-2149.pth" #hard flag 
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-07/10-14-11/detector-399.pth" #soft flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/10-28-40/detector-2099.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-10/08-54-44/detector-799.pth" #hard flag
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-07/15-34-36/detector-272.pth" #hard flag

#episode
attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/attacker-1949.pth" #hard flag 1949
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/detector-1999.pth" #hard flag

#cyclic
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/17-52-41/attacker-1949.pth" #hard flag; cyclic
detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/17-52-41/detector-1999.pth" #hard flag; cyclic

#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/attacker-449.pth" #hard flag 1949
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-499.pth" #hard flag

deterministic_policy: true

defaults:
  # - env_config: config_exp4
  # - env_config: config_exp9
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp_ceaser
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  - env_config: config_exp61
  # - env_config: config_exp62
  # - env_config: config_exp_14_nextline
  - model_config: experiments
