num_episodes: 10
seed: 123 #123 1234 12345

exp_name: "/2022-07-26/14-03-38/wandb/run-20220726_140343-2wwnweyz/" # entangle-pool
#exp_name: "2022-07-26/16-25-20/wandb/run-20220726_162520-2jqwd1e9/" # entangle
#cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-13/cyclone.pkl"
cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-23/cyclone.pkl"
#cyclone_path: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/20-23-30/cyclone.pkl"

#fp-2x
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/attacker-1949.pth" #hard flag 1949
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-11/14-04-52/detector-1999.pth" #hard flag

#cyclic-fp-2x
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/17-52-41/attacker-1949.pth" #hard flag; cyclic
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-09/17-52-41/detector-1999.pth" #hard flag; cyclic

#IBR-PPO############################################
#ibr-fp-5x-1
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-23/attacker-1949.pth" #hard flag; cyclic
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-23/detector-1999.pth" #hard flag; cyclic
#ibr-fp-5x-2
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-28/attacker-1949.pth" #hard flag; cyclic
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-28/detector-1999.pth" #hard flag; cyclic
#ibr-fp-5x-3
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-43/attacker-1949.pth" #hard flag; cyclic
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-14/22-23-43/detector-1999.pth" #hard flag; cyclic

#FP-PPO############################################
#fp-5x-1
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-22-12/detector-1999.pth" #hard flag
#fp-5x-2
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-27/detector-1999.pth" #hard flag
#fp-5x-3
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-13/19-42-31/detector-1999.pth" #hard flag
#fp-5x-4
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-22/06-08-36/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-22/06-08-36/detector-1999.pth" #hard flag
#fp-5x-5
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/09-36-29/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/10-12-48/detector-899.pth" #hard flag
#fp-5x-6
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-21/09-36-29/attacker-1949.pth" #hard flag 5*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-25/22-41-23/detector-1599.pth" #hard flag



#fp-3x
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-21-35/attacker-1849.pth" #hard flag 3*fp
detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-08-29/21-21-35/detector-1899.pth" #hard flag
attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-27/18-19-05/attacker-1949.pth" #hard flag 3*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-27/18-19-05/detector-2499.pth" #hard flag
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-27/18-19-12/attacker-1949.pth" #hard flag 3*fp
#detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-27/18-19-12/detector-2499.pth" #hard flag

#AutoCAT###########################################
#AutoCAT-1
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-18/15-55-27/ppo_agent-99.pth" # AutoCAT attacker
#AutoCAT-2
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-18/15-55-45/ppo_agent-99.pth" # AutoCAT attacker
#AutoCAT-3
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-18/15-55-55/ppo_agent-99.pth" # AutoCAT attacker


#AutoCAT
#attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-09-06/08-22-47/ppo_agent-450.pth" # AutoCAT attacker

deterministic_policy: true

defaults:
  # - env_config: config_exp4
  # - env_config: config_exp9
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp_ceaser
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  # - env_config: config_exp61
  - env_config: config_exp62
  # - env_config: config_exp_14_nextline
  - model_config: experiments
