num_episodes: 10
seed: 1234

exp_name: "/2022-07-26/14-03-38/wandb/run-20220726_140343-2wwnweyz/"
attacker_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-07-26/16-25-20/wandb/run-20220726_162520-2jqwd1e9/files/attacker-model-99.th"
detector_checkpoint: "/private/home/jxcui/CacheSimulator/src/rlmeta/outputs/2022-07-26/16-25-20/wandb/run-20220726_162520-2jqwd1e9/files/detector-model-199.th"
deterministic_policy: true

defaults:
  # - env_config: config_exp4
  # - env_config: config_exp9
  # - env_config: config_exp9_nextline
  # - env_config: config_exp9_stream
  # - env_config: config_exp_ceaser
  # - env_config: config_exp_13
  # - env_config: config_exp_13_nextline
  # - env_config: config_exp_14
  - env_config: config_exp61
  # - env_config: config_exp_14_nextline
  - model_config: experiments
